name: Simple TODO Deploy

on:
  push:
    branches:
      - main 
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push Docker image
        run: |
          docker login -u "${{ secrets.USER }}" -p "${{ secrets.REPO_TOKEN }}" "${{ secrets.REPOSITORY }}"
          docker build -t "${{ secrets.REPOSITORY }}/${{ secrets.USER }}/simple-todo" .
          docker push "${{ secrets.REPOSITORY }}/${{ secrets.USER }}/simple-todo"
